apiVersion: v1
kind: Service
metadata:
  name: kagent-controller-external
  namespace: kagent
  labels:
    app: kagent-controller-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/name: kagent-enterprise
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: a2a
