apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - credit-assessment-agent.yaml
  - bank-credit-limit-agent.yaml

commonLabels:
  app.kubernetes.io/name: bank-agents
  app.kubernetes.io/component: agents
  app.kubernetes.io/part-of: bank-credit-limit-demo

namespace: kagent
